/* Generated By:JavaCC: Do not edit this line. BladeLexerConstants.java */
package org.radic.nb.php.blade.jcclexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BladeLexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int UNEXPECTED_CHARACTER = 9;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"{{--\"",
    "\"--}}\"",
    "<token of kind 8>",
    "<UNEXPECTED_CHARACTER>",
  };

}
